In [1]:
import pandas as pd

In [2]:
# Con esta linea de código verificamos el tipo de separación del csv.
# y si las palabras contienen tildes.

with open('../data/raw/exportaciones_por_pais.csv', encoding='latin-1') as f:
    for i, line in enumerate(f):
        print(i, line)
        if i > 5:
            break

0 "SERIES","Exportaciones por países. BH51101","Exportaciones por países. BH51102","Exportaciones por países. BH51103","Exportaciones por países. BH51104","Exportaciones por países. BH51105","Exportaciones por países. BH51106","Exportaciones por países. BH51107","Exportaciones por países. BH51108","Exportaciones por países. BH51109","Exportaciones por países. BH51110","Exportaciones por países. BH51111","Exportaciones por países. BH51112","Exportaciones por países. BH51113","Exportaciones por países. BH51114"

1 "DESCRIPCIÓN","América. América del Norte. Estados Unidos","América. América del Norte. México","América. América del Norte. Canadá","América. América del Norte. Total","América. América del Sur. Brasil","América. América del Sur. Argentina","América. América del Sur. Total","Total América Exportaciones","Europa. Unión Europea","Europa. Total","Asia. China","Asia. Japón","Asia. Corea del Sur","Asia. Total"

2 "UNIDAD","Millones de dólares FOB","Millones de dólares FOB","Millones de dólares FOB","Millones de dólares FOB","Millones de dólares FOB","Millones de dólares FOB","Millones de dólares FOB","Millones de dólares FOB","Millones de dólares FOB","Millones de dólares FOB","Millones de dólares FOB","Millones de dólares FOB","Millones de dólares FOB","Millones de dólares FOB"

3 "ENE2003","436.85444651","72.17491181","18.24114238","527.2705007","50.887365297","18.497333773","225.0239582","790.34325672","363.71835125","389.80546966","122.73075","254.14534076","60.436042396","525.96477839"

4 "FEB2003","313.62611579","70.03558571","14.51432547","398.17602697","65.00962328","19.77017082","236.89178272","672.74777029","352.63715097","361.61777262","142.71080821","179.98706592","94.00980806","530.27918555"

5 "MAR2003","428.21924859","64.777542662","15.964151516","508.96094277","61.391728812","21.396751584","248.64610732","788.74877243","465.03075343","491.17478949","126.28406759","201.95699089","89.76580713","551.40498894"

6 "ABR2003","367.56548411","76.153028983","57.7705648","501.48907789","57.333226579","20.33578349","245.42073987","788.64790965","488.02914566","511.48606071","142.09876167","124.66873534","81.339976372","471.33887828"

In [3]:
df = pd.read_csv(
    '../data/raw/exportaciones_por_pais.csv',
    encoding='latin-1',
    skiprows=[0, 2]
)

df = df.rename({'DESCRIPCIÓN':'periodo'}, axis=1)

In [4]:
df.head()

,periodo,América. América del Norte. Estados Unidos,América. América del Norte. México,América. América del Norte. Canadá,América. América del Norte. Total,América. América del Sur. Brasil,América. América del Sur. Argentina,América. América del Sur. Total,Total América Exportaciones,Europa. Unión Europea,Europa. Total,Asia. China,Asia. Japón,Asia. Corea del Sur,Asia. Total
0,ENE2003,436.854447,72.174912,18.241142,527.270501,50.887365,18.497334,225.023958,790.343257,363.718351,389.805470,122.730750,254.145341,60.436042,525.964778
1,FEB2003,313.626116,70.035586,14.514325,398.176027,65.009623,19.770171,236.891783,672.747770,352.637151,361.617773,142.710808,179.987066,94.009808,530.279186
2,MAR2003,428.219249,64.777543,15.964152,508.960943,61.391729,21.396752,248.646107,788.748772,465.030753,491.174789,126.284068,201.956991,89.765807,551.404989
3,ABR2003,367.565484,76.153029,57.770565,501.489078,57.333227,20.335783,245.420740,788.647910,488.029146,511.486061,142.098762,124.668735,81.339976,471.338878
4,MAY2003,280.545385,75.027239,45.608372,401.180996,76.748804,25.491596,292.811537,729.683166,465.303198,527.736468,190.391726,209.111321,71.617861,603.060827

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 282 entries, 0 to 281
Data columns (total 15 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   periodo                                     282 non-null    str
 1   América. América del Norte. Estados Unidos  282 non-null    float64
 2   América. América del Norte. México          282 non-null    float64
 3   América. América del Norte. Canadá          282 non-null    float64
 4   América. América del Norte. Total           282 non-null    float64
 5   América. América del Sur. Brasil            282 non-null    float64
 6   América. América del Sur. Argentina         282 non-null    float64
 7   América. América del Sur. Total             282 non-null    float64
 8   Total América Exportaciones                 282 non-null    float64
 9   Europa. Unión Europea                       282 non-null    float64
 10  Europa. Total                               282 non-null    float64
 11  Asia. China                                 282 non-null    float64
 12  Asia. Japón                                 282 non-null    float64
 13  Asia. Corea del Sur                         282 non-null    float64
 14  Asia. Total                                 282 non-null    float64
dtypes: float64(14), str(1)
memory usage: 33.2 KB

In [6]:
# Dic de parseo fechas
meses = {
    'ENE':'01', 'FEB':'02',
    'MAR':'03', 'ABR':'04',
    'MAY':'05', 'JUN':'06',
    'JUL':'07', 'AGO':'08',
    'SEP':'09', 'OCT':'10',
    'NOV':'11', 'DIC':'12'
}

In [7]:
def parear_periodo(periodo):
    mes_abr = periodo[:3]
    anio = periodo[3:]
    return f'{anio}-{meses[mes_abr]}-01'

df['periodo'] = pd.to_datetime(df['periodo'].apply(parear_periodo))

In [8]:
df.head()

,periodo,América. América del Norte. Estados Unidos,América. América del Norte. México,América. América del Norte. Canadá,América. América del Norte. Total,América. América del Sur. Brasil,América. América del Sur. Argentina,América. América del Sur. Total,Total América Exportaciones,Europa. Unión Europea,Europa. Total,Asia. China,Asia. Japón,Asia. Corea del Sur,Asia. Total
0,2003-01-01,436.854447,72.174912,18.241142,527.270501,50.887365,18.497334,225.023958,790.343257,363.718351,389.805470,122.730750,254.145341,60.436042,525.964778
1,2003-02-01,313.626116,70.035586,14.514325,398.176027,65.009623,19.770171,236.891783,672.747770,352.637151,361.617773,142.710808,179.987066,94.009808,530.279186
2,2003-03-01,428.219249,64.777543,15.964152,508.960943,61.391729,21.396752,248.646107,788.748772,465.030753,491.174789,126.284068,201.956991,89.765807,551.404989
3,2003-04-01,367.565484,76.153029,57.770565,501.489078,57.333227,20.335783,245.420740,788.647910,488.029146,511.486061,142.098762,124.668735,81.339976,471.338878
4,2003-05-01,280.545385,75.027239,45.608372,401.180996,76.748804,25.491596,292.811537,729.683166,465.303198,527.736468,190.391726,209.111321,71.617861,603.060827

In [9]:
df.dtypes['periodo']

dtype('<M8[us]')

In [10]:
df['periodo'].min(), df['periodo'].max()

(Timestamp('2003-01-01 00:00:00'), Timestamp('2026-06-01 00:00:00'))

In [11]:
columnas_totales = [c for c in df.columns if 'Total' in c]
columnas_paises = [c for c in df.columns if c not in columnas_totales and c != 'periodo']

print(columnas_totales)
print(columnas_paises)

['América. América del Norte. Total', 'América. América del Sur. Total', 'Total América Exportaciones', 'Europa. Total', 'Asia. Total']
['América. América del Norte. Estados Unidos', 'América. América del Norte. México', 'América. América del Norte. Canadá', 'América. América del Sur. Brasil', 'América. América del Sur. Argentina', 'Europa. Unión Europea', 'Asia. China', 'Asia. Japón', 'Asia. Corea del Sur']

In [12]:
df_paises = df.melt(
    id_vars='periodo',
    value_vars=columnas_paises,
    var_name='destino',
    value_name='exportaciones_musd'
)

df_totales = df.melt(
    id_vars='periodo',
    value_vars=columnas_totales,
    var_name='region',
    value_name='exportaciones_musd'
)

df_paises.head()

     periodo                                     destino  exportaciones_musd
0 2003-01-01  América. América del Norte. Estados Unidos          436.854447
1 2003-02-01  América. América del Norte. Estados Unidos          313.626116
2 2003-03-01  América. América del Norte. Estados Unidos          428.219249
3 2003-04-01  América. América del Norte. Estados Unidos          367.565484
4 2003-05-01  América. América del Norte. Estados Unidos          280.545385

In [16]:
partes = df_paises['destino'].str.split('. ', expand=True, regex=False)
partes.columns = ['continente', 'subregion', 'pais']
partes.head()

  continente          subregion            pais
0    América  América del Norte  Estados Unidos
1    América  América del Norte  Estados Unidos
2    América  América del Norte  Estados Unidos
3    América  América del Norte  Estados Unidos
4    América  América del Norte  Estados Unidos

In [17]:
df_paises = pd.concat([df_paises, partes], axis=1)
df_paises[df_paises['continente'] == 'Europa']['pais'].unique()

<StringArray>
[nan]
Length: 1, dtype: str

In [18]:
df_paises.loc[df_paises['pais'].isna(), 'pais'] = (
    df_paises.loc[df_paises['pais'].isna(), 'subregion']
)
df_paises[df_paises['continente'] == 'Europa'].head()

,periodo,destino,exportaciones_musd,continente,subregion,pais
1410,2003-01-01,Europa. Unión Europea,363.718351,Europa,Unión Europea,Unión Europea
1411,2003-02-01,Europa. Unión Europea,352.637151,Europa,Unión Europea,Unión Europea
1412,2003-03-01,Europa. Unión Europea,465.030753,Europa,Unión Europea,Unión Europea
1413,2003-04-01,Europa. Unión Europea,488.029146,Europa,Unión Europea,Unión Europea
1414,2003-05-01,Europa. Unión Europea,465.303198,Europa,Unión Europea,Unión Europea

In [20]:
mask_dos_niveles = df_paises['subregion'] == df_paises['pais']
df_paises.loc[mask_dos_niveles, 'subregion'] = None
df_paises[['continente', 'subregion', 'pais']].drop_duplicates()

     continente          subregion            pais
0       América  América del Norte  Estados Unidos
282     América  América del Norte          México
564     América  América del Norte          Canadá
846     América    América del Sur          Brasil
1128    América    América del Sur       Argentina
1410     Europa                NaN   Unión Europea
1692       Asia                NaN           China
1974       Asia                NaN           Japón
2256       Asia                NaN   Corea del Sur