In [1]:
import sys
sys.path.append('..')

from src.bq_utils import load_queries, run

Q = load_queries()
list(Q)

['P1a',
 'P1b',
 'P1c',
 'P2',
 'P3',
 'P4a',
 'P4b',
 'P5a',
 'P5b',
 'P5c',
 'P6',
 'P6b',
 'P7',
 'P8a',
 'P8b',
 'P9',
 'P10',
 'P11',
 'P12a',
 'P12b',
 'P13']

In [2]:
df = run(Q['P1a'])
df

   filas_totales  filas_distintas
0          41188            41176

In [3]:
df = run(Q['P1b'])
df

,age_nulos,job_nulos,marital_nulos,education_nulos,default_credit_nulos,housing_nulos,loan_nulos,contact_nulos,month_nulos,day_of_week_nulos,...,campaign_nulos,pdays_nulos,previous_nulos,poutcome_nulos,emp_var_rate_nulos,cons_price_idx_nulos,cons_conf_idx_nulos,euribor3m_nulos,nr_employed_nulos,y_nulos
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
df = run(Q['P1c'])
df

   edad_min  edad_max  campaign_min  campaign_max  euribor_min  euribor_max
0        17        98             1            56        0.634        5.045

In [5]:
df = run(Q['P2'])
df

         variable  pct_unknown
0  default_credit       0.2087
1       education       0.0420
2         housing       0.0240
3            loan       0.0240
4             job       0.0080
5         marital       0.0019

In [6]:
df = run(Q['P3'])
df

   total_contactos  total_contrataciones  tasa_conversion
0            41188                  4640           0.1127

In [7]:
df = run(Q['P4a'])
df

      grupo      n  tasa_conversion
0  grupo_H4   2949           0.1780
1     resto  38239           0.1076

In [8]:
df = run(Q['P4b'])
df

              job      n  tasa_conversion
0         student    875           0.3143
1         retired   1720           0.2523
2      unemployed   1014           0.1420
3          admin.  10422           0.1297
4      management   2924           0.1122
5         unknown    330           0.1121
6      technician   6743           0.1083
7   self-employed   1421           0.1049
8       housemaid   1060           0.1000
9    entrepreneur   1456           0.0852
10       services   3969           0.0814
11    blue-collar   9254           0.0689

In [9]:
df = run(Q['P5a'])
df

             education      n  tasa_conversion
0           illiterate     18           0.2222
1              unknown   1731           0.1450
2    university.degree  12168           0.1372
3  professional.course   5243           0.1135
4          high.school   9515           0.1084
5             basic.4y   4176           0.1025
6             basic.6y   2292           0.0820
7             basic.9y   6045           0.0782

In [10]:
df = run(Q['P5b'])
df

    marital      n  tasa_conversion
0   unknown     80           0.1500
1    single  11568           0.1400
2  divorced   4612           0.1032
3   married  24928           0.1016

In [11]:
df = run(Q['P5c'])
df

              job            education     n  tasa_conversion
0         student              unknown   167           0.3533
1         student          high.school   357           0.3193
2         retired             basic.4y   597           0.3099
3         retired  professional.course   241           0.2365
4         retired    university.degree   285           0.2316
5         retired          high.school   276           0.2246
6         student    university.degree   170           0.2059
7      management              unknown   123           0.1626
8          admin.              unknown   249           0.1526
9        services    university.degree   173           0.1503
10     unemployed    university.degree   262           0.1489
11         admin.    university.degree  5753           0.1431
12     unemployed             basic.4y   112           0.1429
13     unemployed  professional.course   142           0.1408
14     unemployed             basic.9y   186           0.1398
15         admin.  professional.course   363           0.1350
16     unemployed          high.school   259           0.1313
17        retired             basic.9y   145           0.1310
18        unknown              unknown   131           0.1298
19       services              unknown   150           0.1267
20  self-employed    university.degree   765           0.1255
21     management    university.degree  2063           0.1246
22     technician    university.degree  1809           0.1244
23      housemaid    university.degree   139           0.1223
24  self-employed  professional.course   168           0.1190
25     technician              unknown   212           0.1179
26         admin.          high.school  3329           0.1147
27   entrepreneur    university.degree   610           0.1082
28      housemaid             basic.4y   474           0.1076
29    blue-collar          high.school   878           0.1071
30     technician  professional.course  3320           0.1033
31     technician          high.school   873           0.0974
32     technician             basic.9y   384           0.0964
33    blue-collar  professional.course   453           0.0905
34       services             basic.6y   226           0.0885
35       services  professional.course   218           0.0872
36         admin.             basic.9y   499           0.0842
37  self-employed             basic.9y   220           0.0818
38      housemaid          high.school   174           0.0805
39       services          high.school  2682           0.0757
40    blue-collar             basic.6y  1426           0.0750
41       services             basic.9y   388           0.0747
42   entrepreneur          high.school   234           0.0684
43  self-employed          high.school   118           0.0678
44   entrepreneur  professional.course   135           0.0667
45     management             basic.9y   166           0.0663
46    blue-collar             basic.9y  3623           0.0662
47   entrepreneur             basic.9y   210           0.0571
48     management          high.school   298           0.0570
49    blue-collar             basic.4y  2318           0.0531
50       services             basic.4y   132           0.0530
51         admin.             basic.6y   151           0.0530
52    blue-collar              unknown   454           0.0529
53   entrepreneur             basic.4y   137           0.0511
54     management             basic.4y   100           0.0500

In [12]:
df = run(Q['P6'])
df

  tramo_edad      n  tasa_conversion
0      1_<25   1068           0.2397
1    2_25-34  13686           0.1217
2    3_35-44  13500           0.0865
3    4_45-54   8704           0.0865
4    5_55-64   3567           0.1357
5      6_65+    663           0.4721

In [13]:
df = run(Q['P6b'])
df

  tramo_edad   marital      n  tasa_conversion
0      1_<35  divorced    780           0.0821
1      1_<35   married   6341           0.0982
2      1_<35    single   7596           0.1618
3    2_35-49  divorced   2381           0.0848
4    2_35-49   married  12467           0.0808
5    2_35-49    single   3510           0.0957
6      3_50+  divorced   1451           0.1447
7      3_50+   married   6120           0.1474
8      3_50+    single    462           0.1190

In [14]:
df = run(Q['P7'])
df

   housing     loan      n  tasa_conversion
0       no       no  16065           0.1091
1       no      yes   2557           0.1072
2  unknown  unknown    990           0.1081
3      yes       no  17885           0.1173
4      yes      yes   3691           0.1108

In [15]:
df = run(Q['P8a'])
df

  month      n  tasa_conversion
0   may  13769           0.0643
1   jul   7174           0.0905
2   aug   6178           0.1060
3   jun   5318           0.1051
4   nov   4101           0.1014
5   apr   2632           0.2048
6   oct    718           0.4387
7   sep    570           0.4491
8   mar    546           0.5055
9   dec    182           0.4890

In [16]:
df = run(Q['P8b'])
df

  day_of_week     n  tasa_conversion
0         thu  8623           0.1212
1         mon  8514           0.0995
2         wed  8134           0.1167
3         tue  8090           0.1178
4         fri  7827           0.1081

In [17]:
df = run(Q['P9'])
df

     contact      n  tasa_conversion
0  telephone  15044           0.0523
1   cellular  26144           0.1474

In [18]:
df = run(Q['P10'])
df

   intento      n  tasa_conversion
0        1  17642           0.1304
1        2  10570           0.1146
2        3   5341           0.1075
3        4   2651           0.0939
4        5   1599           0.0750
5        6    979           0.0766
6        7   2406           0.0461

In [19]:
df = run(Q['P11'])
df

      poutcome   historial_pdays      n  tasa_conversion
0      failure  contactado_antes    142           0.5141
1      failure  nunca_contactado   4110           0.1294
2  nonexistent  nunca_contactado  35563           0.0883
3      success  contactado_antes   1373           0.6511

In [20]:
df = run(Q['P12a'])
df

,bloque,desde,hasta,n,tasa_conversion,euribor_prom,emp_var_prom,nr_employed_prom
0,1,0,4118,4119,0.0277,4.86,1.10,5191.0
1,2,4119,8237,4119,0.0352,4.86,1.13,5195.0
2,3,8238,12356,4119,0.0422,4.94,1.40,5228.0
3,4,12357,16475,4119,0.0663,4.96,1.40,5228.0
4,5,16476,20594,4119,0.0624,4.96,1.40,5228.0
5,6,20595,24713,4119,0.0546,4.84,1.14,5222.0
6,7,24714,28832,4119,0.1017,3.37,-0.57,5169.0
7,8,28833,32951,4119,0.1197,1.35,-1.80,5099.0
8,9,32952,37069,4118,0.1574,1.26,-2.03,5094.0
9,10,37070,41187,4118,0.4594,0.80,-2.36,5015.0

In [21]:
df = run(Q['P12b'])
df

   empvar_euribor  empvar_nremp  euribor_nremp  ipc_empvar  confianza_euribor
0           0.972         0.907          0.945       0.775              0.278

In [22]:
df = run(Q['P13'])
df

   euribor_tramo      n  tasa_conversion
0              0   3890           0.4571
1              1   9608           0.1585
2              3     14           0.0714
3              4  27660           0.0481
4              5     16           0.5000